name: redux_watch
description: A starting point for Dart libraries or applications.
version: 0.1.2
homepage: "https://github.com/ga6559/redux_watch"
author: Gustavo <ga6559@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  redux: ^3.0.0

dev_dependencies:
  test: ^0.12.0
